name: Flutter CI/CD

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build Flutter APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.27.4

      - name: Install Dependencies
        run: flutter pub get

      - name: Get Commit Hash
        id: commit
        run: echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build APK
        run: flutter build apk --release

      - name: Buat Folder Assets Release
        run: mkdir -p assets/release

      - name: Pindahkan APK ke Assets Release dengan Nama Berformat
        run: mv build/app/outputs/flutter-apk/app-release.apk assets/release/app-release-${{ env.COMMIT_HASH }}.apk

      - name: Upload Artifact (APK)
        uses: actions/upload-artifact@v4
        with:
          name: Flutter APK ${{ env.COMMIT_HASH }}
          path: assets/release/app-release-${{ env.COMMIT_HASH }}.apk

      - name: Buat GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v1.0.${{ github.run_number }}-${{ env.COMMIT_HASH }}
          name: "Release v1.0.${{ github.run_number }}-${{ env.COMMIT_HASH }}"
          body: |
            🚀 **Flutter APK Release**
            - Commit: `${{ env.COMMIT_HASH }}`
            - Branch: `${{ github.ref_name }}`
          files: assets/release/app-release-${{ env.COMMIT_HASH }}.apk
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}